sylius_import_export.admin.resource.export:
    path: /export/{grid}
    methods: [POST]
    defaults:
        _controller: sylius_import_export.controller.export_action
        _sylius:
            filterable: true

sylius_grid_import_export_admin_process:
    resource: |
        alias: sylius_grid_import_export.process
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show', 'create', 'update']
        redirect: index
        grid: sylius_grid_import_export_admin_process
        permission: true
    type: sylius.resource

sylius_grid_import_export_admin_process_show:
    path: /import-export/processes/{id}
    methods: [ GET ]
    defaults:
        _controller: sylius_grid_import_export.controller.process::showAction
        _sylius:
            section: admin
            template: '@SyliusAdmin/shared/crud/show.html.twig'
            permission: true
            vars:
                hook_prefix: 'sylius_grid_import_export.admin.process'

sylius_grid_import_export_admin_process_download:
    path: /import-export/processes/{uuid}/download
    methods: [ GET ]
    defaults:
        _controller: sylius_import_export.controller.download_export_action
        _sylius:
            section: admin
            permission: true
