sylius_import_export.admin.resource.export:
    path: /export/{grid}
    methods: [POST]
    defaults:
        _controller: sylius_import_export.controller.export_action
        _sylius:
            filterable: true

sylius_grid_import_export_admin_process_export:
    resource: |
        alias: sylius_grid_import_export.process_export
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show', 'create', 'update']
        redirect: index
        grid: sylius_grid_import_export_admin_process_export
        permission: true
        path: /import-export/exports
    type: sylius.resource

sylius_grid_import_export_admin_process_export_show:
    path: /import-export/exports/{id}
    methods: [ GET ]
    defaults:
        _controller: sylius_grid_import_export.controller.process_export::showAction
        _sylius:
            section: admin
            template: '@SyliusAdmin/shared/crud/show.html.twig'
            permission: true
            vars:
                hook_prefix: 'sylius_grid_import_export.admin.process_export'

sylius_grid_import_export_admin_process_export_download:
    path: /import-export/exports/{uuid}/download
    methods: [ GET ]
    defaults:
        _controller: sylius_import_export.controller.download_export_action
        _sylius:
            section: admin
            permission: true
