sylius_resource:
    resources:
        sylius_import_export.process_export:
            driver: doctrine/orm
            classes:
                model: Sylius\ImportExport\Entity\ExportProcess
                interface: Sylius\ImportExport\Entity\ExportProcessInterface
