sylius_grid:
    grids:
        sylius_import_export_admin_process_import:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\ImportExport\Entity\ImportProcess
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                format:
                    type: string
                    label: sylius_import_export.ui.format
                resource:
                    type: string
                    label: sylius_import_export.ui.resource
                importedCount:
                    type: string
                    label: sylius_import_export.ui.imported_count
                status:
                    type: twig
                    label: sylius.ui.status
                    options:
                        template: '@SyliusImportExport\admin\import_export\grid\field\status.html.twig'
            actions:
                item:
                    show:
                        type: show