sylius_resource:
    resources:
        sylius_grid_import_export.process:
            driver: doctrine/orm
            classes:
                model: Sylius\GridImportExport\Entity\Process
                interface: Sylius\GridImportExport\Entity\ProcessInterface
